import React from 'react';
import { motion } from 'framer-motion';
import { ChevronRight, Activity, Sparkles, TrendingUp, Heart, Zap } from 'lucide-react';

const Hero = ({ onStart }) => {
  const features = [
    { icon: Sparkles, text: "AI-Powered Plans" },
    { icon: TrendingUp, text: "Track Progress" },
    { icon: Heart, text: "Personalized Nutrition" },
    { icon: Zap, text: "Instant Results" }
  ];

  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }} 
      animate={{ opacity: 1, y: 0 }} 
      exit={{ opacity: 0, y: -20 }}
      className="text-center mt-10 md:mt-20 px-4"
    >
      {/* Animated Icon */}
      <motion.div 
        className="flex justify-center mb-6 sm:mb-8"
        initial={{ scale: 0 }}
        animate={{ scale: 1 }}
        transition={{ type: "spring", stiffness: 200, damping: 15 }}
      >
        <div className="relative">
          <div className="absolute inset-0 bg-blue-500 rounded-full blur-2xl opacity-30 animate-pulse"></div>
          <div className="relative p-4 sm:p-6 bg-gradient-to-br from-blue-600/30 to-purple-600/30 rounded-full backdrop-blur-sm border border-blue-500/20">
            <Activity size={40} className="sm:w-14 sm:h-14 text-blue-400" />
          </div>
        </div>
      </motion.div>
      
      {/* Main Heading */}
      <motion.h1 
        className="text-3xl sm:text-4xl md:text-5xl lg:text-7xl xl:text-8xl font-extrabold mb-4 sm:mb-6 tracking-tight px-2"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
      >
        <span className="text-white block sm:inline">Your AI </span>
        <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 via-purple-400 to-pink-400 animate-gradient block sm:inline">
          Fitness Coach
        </span>
      </motion.h1>
      
      {/* Subtitle */}
      <motion.p 
        className="text-base sm:text-lg md:text-xl lg:text-2xl text-slate-300 mb-3 sm:mb-4 max-w-3xl mx-auto leading-relaxed px-4"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.3 }}
      >
        Get a fully personalized workout and diet plan generated by <span className="text-blue-400 font-semibold">Artificial Intelligence</span> in seconds.
      </motion.p>
      
      <motion.p 
        className="text-xs sm:text-sm md:text-base text-slate-500 mb-6 sm:mb-10 max-w-2xl mx-auto px-4"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.4 }}
      >
        No guesswork. No confusion. Just science-backed plans tailored to your goals.
      </motion.p>

      {/* Feature Pills */}
      <motion.div 
        className="flex flex-wrap justify-center gap-2 sm:gap-3 mb-6 sm:mb-10 px-2 sm:px-4"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.5 }}
      >
        {features.map((feature, index) => {
          const Icon = feature.icon;
          return (
            <motion.div
              key={index}
              className="flex items-center gap-1.5 sm:gap-2 px-3 sm:px-4 py-1.5 sm:py-2 bg-slate-800/50 backdrop-blur-sm border border-slate-700/50 rounded-full text-slate-300 text-xs sm:text-sm"
              whileHover={{ scale: 1.05, borderColor: 'rgb(59 130 246)' }}
              whileTap={{ scale: 0.95 }}
              transition={{ type: "spring", stiffness: 400 }}
            >
              <Icon size={14} className="sm:w-4 sm:h-4 text-blue-400" />
              <span className="whitespace-nowrap">{feature.text}</span>
            </motion.div>
          );
        })}
      </motion.div>
      
      {/* CTA Button */}
      <motion.button 
        onClick={onStart} 
        className="group relative inline-flex items-center justify-center px-6 sm:px-10 py-3 sm:py-5 font-bold text-base sm:text-lg text-white transition-all duration-300 bg-gradient-to-r from-blue-600 via-purple-600 to-pink-600 rounded-full hover:from-blue-500 hover:via-purple-500 hover:to-pink-500 active:scale-95 focus:outline-none ring-offset-2 focus:ring-2 ring-blue-400 shadow-2xl shadow-blue-500/50 touch-manipulation"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.6 }}
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
      >
        <span className="relative z-10 flex items-center gap-2">
          <span className="hidden sm:inline">Start Your Transformation</span>
          <span className="sm:hidden">Get Started</span>
          <ChevronRight className="ml-1 group-hover:translate-x-1 transition-transform w-4 h-4 sm:w-5 sm:h-5" />
        </span>
        <div className="absolute inset-0 rounded-full bg-gradient-to-r from-blue-400 to-purple-400 opacity-0 group-hover:opacity-20 blur-xl transition-opacity"></div>
      </motion.button>

      {/* Trust Indicators */}
      <motion.div 
        className="mt-8 sm:mt-12 text-xs sm:text-sm text-slate-500 px-4"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.8 }}
      >
        <p className="flex flex-wrap justify-center gap-2 sm:gap-4">
          <span>✨ Free to use</span>
          <span className="hidden sm:inline">•</span>
          <span>🔒 Secure & Private</span>
          <span className="hidden sm:inline">•</span>
          <span>⚡ Instant Results</span>
        </p>
      </motion.div>
    </motion.div>
  );
};

export default Hero;